.TH LEO 1 "21 November 2020" "v0.5.1"

.SH NAME
leo \- a simple backup program

.SH SYNOPSIS
.B leo
[-hpPvV] profiles
.P

.SH DESRIPTION
.B leo
is a simple backup program. It creates tar(1) files from a pre-defined
list. It can encrypt/sign files with gpg2(1) & sign files with
signify(1).

I use this to quickly backup some of my files. It works on profiles,
profiles are simple lists of files which get backed up.
.SH PROFILE
Profile is a simple hash table which contains the list of profiles.
The profiles are mapped to a list of file paths which are to be backed
up.
.SH OPTIONS
The options are as follows:
.TP
.B -h
Print help.
.TP
.B -p
Print profiles.
.TP
.B -P
Print profiles with all the files to backup/exclude.
.TP
.B -v
Increase verbosity.
.TP
.B -V
Print version.
.TP
.SH AUTHOR
Andinus <andinus@nand.sh>
